import React from "react";
import "../styles/ComplainForm.css";


const ComplaintForm = () => {
  return (

    <div className="form-container">
      
      <h2>Complaint Onboarding</h2>
      <form className="complaint-form">
        <div className="form-group">
          <label>Request Reference:</label>
          <input type="text" value="AutoGenerated123" disabled />
        </div>

        <div className="form-group">
          <label>Category Type ID:</label>
          <input type="text" placeholder="Category ID" />
        </div>

        <div className="form-group">
          <label>Medium:</label>
          <select>
            <option value="">Select Medium</option>
            <option>Hotline</option>
            <option>Customer</option>
            <option>Email</option>
            <option>WhatsApp</option>
            <option>SMS</option>
          </select>
        </div>

        <div className="form-group">
          <label>Medium Source:</label>
          <input type="text" placeholder="Source Info" />
        </div>

        <div className="form-group">
          <label>Document:</label>
          <input type="file" />
        </div>

        <div className="form-group">
          <label>Document Reference:</label>
          <input type="text" placeholder="Document Ref" />
        </div>

        <div className="form-group">
          <label>Remark:</label>
          <input type="text" placeholder="Enter remarks" />
        </div>

        <div className="form-group checkbox-group">
          <label>Repeat Complaint:</label>
          <input type="checkbox" />
        </div>

        <div className="form-group">
          <label>Organization:</label>
          <select>
            <option>Select Organization</option>
            <option>SLT</option>
            <option>Mobitel</option>
          </select>
        </div>

        <div className="form-group">
          <label>Project Type:</label>
          <input type="text" placeholder="Project Type" />
        </div>

        <div className="form-group">
          <label>Project:</label>
          <input type="text" placeholder="Project" />
        </div>

        <div className="form-actions">
          <button type="reset" className="clear-btn">Clear</button>
          <button type="submit" className="submit-btn">Submit</button>
        </div>
      </form>
    </div>
    
  );
};

export default ComplaintForm;
